<?php // the list parts generated by the shop ?>

<?php foreach($jr_groupArray as $grpName => $grpList) : ?>
  <?php $menuHeaderImg = site_url(jr_siteImg('icons/menu-'.strtolower(strtok($grpName, ' ')).'.jpg')); ?>
<li>
  <h3 class="nav-btn"><?php echo $grpName ?></h3>
  <ul class="sub-menu" style="background-image:url(<?php echo $menuHeaderImg; ?>)">
    <h3 class="touch-toggle btn-red text-icon close-w">Back</h3>

    <?php foreach ($grpList as $category) : $link=site_url( '/products/'.sanitize_title($category['Name'])); ?>
    <li><a class="text-icon nav-btn arrow-r" href="<?php echo $link ?>">
        <?php echo $category['Name'] ?>
    </a></li>
    <?php endforeach ?>

  </ul>
</li>

<?php endforeach ?>
