  <?php // the list parts generated by the shop
  $jr_groupArray = jrCached_Categories_Sorted();
  ?>
  <ul class="main-menu" id="js-main-list" >
    <?php foreach($jr_groupArray as $grpName => $grpList) : ?>
    <?php $menuHeaderImg = site_url(jr_siteImg('icons/menu-'.strtolower(strtok($grpName, ' ')).'.jpg')); ?>

    <li>
      <h3 class="nav-btn"><?php echo $grpName ?></h3>
      <ul class="sub-menu" style="background-image:url(<?php echo $menuHeaderImg; ?>)">
        <h3 class="touch-toggle btn-red text-icon close-w">Back</h3>

        <?php foreach ($grpList as $category) : $link=site_url( '/products/'.sanitize_title($category)); ?>
        <li><a class="text-icon nav-btn arrow-r" href="<?php echo $link ?>">
            <?php echo $category ?>
        </a></li>
        <?php endforeach ?>

      </ul>
    </li>

    <?php endforeach ?>
    <?php // wp menus start here. admin for setup --> ?>

    <li><h3 class="nav-btn">Featured</h3>
      <?php wp_nav_menu(array(
          'container' => '',                           // remove nav container
          'menu' => __( 'Featured Menu Links', 'bonestheme' ),  // nav name
          'before' => '<span class="nav-btn text-icon arrow-r">',
          'after' => '</span>',
          'items_wrap'      => '<ul class="sub-menu" ><h3 class="touch-toggle btn-red text-icon close-w">Back</h3>%3$s</ul>',
          'theme_location' => 'featured-menu',         // where it's located in the theme
          'fallback_cb' => ''                          // fallback function (if there is one)
      )); ?>
    </li>

    <li><h3 class="nav-btn">Other Services</h3>
      <?php wp_nav_menu(array(
          'container' => '',
          'menu' => __( 'Services Menu links', 'bonestheme' ),  // nav name
          'before' => '<span class="nav-btn text-icon arrow-r">',
          'after' => '</span>',
          'items_wrap'      => '<ul class="sub-menu" ><h3 class="touch-toggle btn-red text-icon close-w">Back</h3>%3$s</ul>',
          'theme_location' => 'services-menu',         // where it's located in the theme
          'fallback_cb' => ''                          // fallback function (if there is one)
      )); ?>
    </li>

  </ul>
